### ISSUE TITLE
Hard-coded ERA5 filenames

### ISSUE THREAD

**Issue by liamtoney** [DOI-USGS/volcano-ash3d-metreader#13]
When using MetReader via AVO-G2S with ERA5 files, I get the following error running `g2S_genSC`:
```
 --------------------------------------------------------------------------------
 ----------                MR_Read_Met_Times_netcdf                    ----------
 --------------------------------------------------------------------------------
 MR ERROR: nf90_open: No such file or directory
     Could not open file: ERA5/2016/e5.oper.an.pl.128_129_z.regn320sc.2016052200_2016052223.nc
 Exiting
STOP 1
```
I'm using ERA5 files downloaded from [ds633.0](https://rda.ucar.edu/datasets/ds633.0/index.html#!description) of the RDA. The filename is slightly different:
```
e5.oper.an.pl.128_129_z.ll025sc.2016052200_2016052223.nc
```
instead of
```
e5.oper.an.pl.128_129_z.regn320sc.2016052200_2016052223.nc
``` 
for example.

I think this has to do with [ds630.0](https://rda.ucar.edu/datasets/ds630.0) being deprecated. I will try to just rename my files (`*ll025*` to `*regn320*`) and move forward.

**Comment by hschwaiger-usgs** [comment]
Loading of ERA5 files has been rewritten and generalized. See doc/MetReader_manual.pdf
