### ISSUE TITLE
pre-processing ERA5 rd633.0 wind files

### ISSUE THREAD

**Issue by lgmastin** [DOI-USGS/volcano-ash3d-metreader#16]
I was able to use the metreader to read ERA5 reanalysis wind files downloaded in netcdf format from https://rda.ucar.edu/datasets/ds633.0.  However I had to rename them before using them.  For each day, Metreader expects a set of files, each containing one variable.  An example file containing 3d temperature variable for June 15, 1991 would have the name:
e5.oper.an.pl.128_130_t.ll025sc.1991061500_1991061523.nc
where the 22nd character, "t", denotes the temperature variable, and characters 33-53 denote the starting and ending date and time.  The files downloaded from ucar have longer names:
e5.oper.an.pl.128_135_w.ll025sc.1991061500_1991061523.grb.mastin428224.nc
Characters 54-70 denote the original file format, the downloader's name, and the download number.  These characters must be stripped out before they can be read by metreader.

**Comment by hschwaiger-usgs** [comment]
The loading of ERA5 files has been rewritten and does not require these hardwired paths if the data are downloaded from cds.climate.copernicus.eu.
